---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "benchmark-cluster-queue"
spec:
  # Define the total resources this queue can manage
  namespaceSelector: {}
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 50
      - name: "memory"
        nominalQuota: 100Gi
