{{- if eq .Values.benchmarkTool "guidellm" }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.benchmark.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: llm-d-bench
    job-type: benchmark
    {{- if .Values.kueue.enabled }}
    kueue.x-k-s.io/queue-name: "{{ .Values.kueue.queueName }}"
    {{- end }}
spec:
  {{- if .Values.kueue.enabled }}
  suspend: true
  {{- end }}
  template:
    metadata:
      labels:
        app: llm-d-bench
        job: {{ .Values.benchmark.name }}
    spec:
      containers:
      - name: guidellm
        image: "{{ .Values.benchmark.image.repository }}:{{ .Values.benchmark.image.tag }}"
        imagePullPolicy: {{ .Values.benchmark.image.pullPolicy | quote }}
        args:
          - "--target"
          - "{{ .Values.benchmark.target }}"
          {{- if .Values.benchmark.model }}
          - "--model"
          - "{{ .Values.benchmark.model }}"
          {{- end }}
          {{- if .Values.benchmark.processor }}
          - "--processor"
          - "{{ .Values.benchmark.processor }}"
          {{- end }}
          {{- if .Values.benchmark.rateType }}
          - "--rate-type"
          - "{{ .Values.benchmark.rateType }}"
          {{- end }}
          {{- if .Values.benchmark.rate }}
          - "--rate"
          - "{{ if kindIs "slice" .Values.benchmark.rate }}{{ join "," .Values.benchmark.rate }}{{ else }}{{ .Values.benchmark.rate }}{{ end }}"
          {{- end }}
          {{- if .Values.benchmark.data }}
          - "--data"
          - "{{ if kindIs "slice" .Values.benchmark.data }}{{ join "," .Values.benchmark.data }}{{ else }}{{ .Values.benchmark.data }}{{ end }}"
          {{- end }}
          {{- if .Values.benchmark.maxSeconds }}
          - "--max-seconds"
          - "{{ .Values.benchmark.maxSeconds }}"
          {{- end }}
          {{- if .Values.benchmark.accelerator }}
          - "--accelerator"
          - "{{ .Values.benchmark.accelerator }}"
          {{- end }}
          {{- if .Values.mlflow.experimentName }}
          - "--experiment-name"
          - "{{ .Values.mlflow.experimentName }}"
          {{- end}}
          {{- if .Values.benchmark.additionalArgs }}
          - "{{ .Values.benchmark.additionalArgs }}"
          {{- end }}
        env:
          - name: HF_HOME
            value: "/tmp/.huggingface"
          - name: MLFLOW_TRACKING_INSECURE_TLS
            value: "true"
          - name: HF_CLI_TOKEN
            valueFrom:
              secretKeyRef:
                name: huggingface-token
                key: HF_CLI_TOKEN
          - name: MLFLOW_TRACKING_URI
            value: {{ .Values.mlflow.trackingUri | quote }}
          - name: MLFLOW_TRACKING_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mlflow.auth.secretName }}
                key: {{ .Values.mlflow.auth.usernameKey }}
          - name: MLFLOW_TRACKING_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mlflow.auth.secretName }}
                key: {{ .Values.mlflow.auth.passwordKey }}
          - name: MLFLOW_EXPERIMENT_NAME
            value: {{ .Values.mlflow.experimentName | default .Values.benchmark.name | quote }}
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mlflow.s3.secretName }}
                key: {{ .Values.mlflow.s3.accessKey }}
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mlflow.s3.secretName }}
                key: {{ .Values.mlflow.s3.secretKey }}
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mlflow.s3.secretName }}
                key: {{ .Values.mlflow.s3.regionKey }}
          - name: MLFLOW_S3_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mlflow.s3.secretName }}
                key: {{ .Values.mlflow.s3.bucketNameKey }}
          {{- range $key, $value := .Values.benchmark.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
      restartPolicy: Never
      {{- if .Values.benchmark.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.benchmark.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.benchmark.affinity }}
      affinity:
        {{- toYaml .Values.benchmark.affinity | nindent 8 }}
      {{- end }}
  backoffLimit: 1
{{- end }}
