{{- if and (eq .Values.jobType "benchmark") (eq .Values.benchmarkTool "guidellm") }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.benchmark.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: llm-d-bench
    job-type: benchmark
    {{- if .Values.kueue.enabled }}
    kueue.x-k8s.io/queue-name: "{{ .Values.kueue.queueName }}"
    {{- end }}
spec:
  {{- if .Values.kueue.enabled }}
  suspend: true
  {{- end }}
  template:
    metadata:
      labels:
        app: llm-d-bench
        job: {{ .Values.benchmark.name }}
    spec:
      {{- if .Values.monitoring.enabled }}
      serviceAccountName: {{ .Values.benchmark.name | replace "." "-" }}-sa
      {{- end }}
      {{- if .Values.monitoring.enabled }}
      # Shared emptyDir for container coordination
      initContainers:
      - name: init-coordination
        image: busybox:latest
        command: ['sh', '-c', 'mkdir -p /shared/state && echo "Coordination directory initialized"']
        volumeMounts:
        - name: shared-state
          mountPath: /shared/state
      {{- end }}

      containers:
      # Main benchmark container
      - name: guidellm
        image: "{{ .Values.benchmark.image.repository }}:{{ .Values.benchmark.image.tag }}"
        env:
          - name: HF_CLI_TOKEN
            valueFrom:
              secretKeyRef:
                name: huggingface-token
                key: HF_CLI_TOKEN
          {{- range $key, $value := .Values.benchmark.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        command: ["/bin/bash"]
        args:
          - -c
          - |
            set -euo pipefail

            export RUN_DIR="/results/run_$(date +%s)"
            mkdir -p ${RUN_DIR}
            {{- if .Values.monitoring.enabled }}
            mkdir -p ${RUN_DIR}/metrics
            export STATE_DIR="/shared/state"
            {{- end }}
            export GUIDELLM__LOGGING__LOG_FILE="${RUN_DIR}/console.log"

            echo "[BENCHMARK] Creating cache directory..."
            mkdir -p /results/.huggingface
            export HF_HOME="/results/.huggingface"

            echo "[BENCHMARK] Logging into Hugging Face..."
            hf auth login --token $HF_CLI_TOKEN

            echo "[BENCHMARK] Command: guidellm benchmark run \
              {{- if .Values.benchmark.target }}
              --target {{ .Values.benchmark.target }} \
              {{- end }}
              {{- if .Values.benchmark.model }}
              --model {{ .Values.benchmark.model }} \
              {{- end }}
              {{- if .Values.benchmark.processor }}
              --processor {{ .Values.benchmark.processor }} \
              {{- end }}
              {{- if .Values.benchmark.backendType }}
              --backend-type {{ .Values.benchmark.backendType }} \
              {{- end }}
              {{- if .Values.benchmark.rateType }}
              --rate-type={{ .Values.benchmark.rateType }} \
              {{- end }}
              {{- if .Values.benchmark.rate }}
              --rate={{ if kindIs "slice" .Values.benchmark.rate }}{{ join "," .Values.benchmark.rate }}{{ else }}{{ .Values.benchmark.rate }}{{ end }} \
              {{- end }}
              {{- if .Values.benchmark.data }}
              --data={{ if kindIs "slice" .Values.benchmark.data }}{{ join "," .Values.benchmark.data }}{{ else }}{{ .Values.benchmark.data }}{{ end }} \
              {{- end }}
              {{- if .Values.benchmark.maxSeconds }}
              --max-seconds={{ .Values.benchmark.maxSeconds }} \
              {{- end }}
              {{- if .Values.benchmark.additionalArgs }}
              {{ .Values.benchmark.additionalArgs }} \
              {{- end }}
              --output-path \${RUN_DIR}/output.json"

            {{- if .Values.monitoring.enabled }}
            # Signal monitoring sidecar to start collection
            echo "[BENCHMARK] Signaling monitoring sidecar to start..."
            touch ${STATE_DIR}/.start_collection

            # Wait briefly for monitoring to initialize
            sleep 2
            {{- end }}

            echo "[BENCHMARK] Running guidellm..."
            guidellm benchmark run \
              {{- if .Values.benchmark.target }}
              --target {{ .Values.benchmark.target }} \
              {{- end }}
              {{- if .Values.benchmark.model }}
              --model {{ .Values.benchmark.model }} \
              {{- end }}
              {{- if .Values.benchmark.processor }}
              --processor {{ .Values.benchmark.processor }} \
              {{- end }}
              {{- if .Values.benchmark.backendType }}
              --backend-type {{ .Values.benchmark.backendType }} \
              {{- end }}
              {{- if .Values.benchmark.rateType }}
              --rate-type={{ .Values.benchmark.rateType }} \
              {{- end }}
              {{- if .Values.benchmark.rate }}
              --rate={{ if kindIs "slice" .Values.benchmark.rate }}{{ join "," .Values.benchmark.rate }}{{ else }}{{ .Values.benchmark.rate }}{{ end }} \
              {{- end }}
              {{- if .Values.benchmark.data }}
              --data={{ if kindIs "slice" .Values.benchmark.data }}{{ join "," .Values.benchmark.data }}{{ else }}{{ .Values.benchmark.data }}{{ end }} \
              {{- end }}
              {{- if .Values.benchmark.maxSeconds }}
              --max-seconds={{ .Values.benchmark.maxSeconds }} \
              {{- end }}
              {{- if .Values.benchmark.additionalArgs }}
              {{ .Values.benchmark.additionalArgs }} \
              {{- end }}
              --output-path ${RUN_DIR}/output.json

            echo "[BENCHMARK] Output file checksum:"
            sha256sum "${RUN_DIR}/output.json" || echo "[BENCHMARK] Error: Failed to generate checksum"

            {{- if .Values.monitoring.enabled }}
            # Signal monitoring sidecar to stop collection
            echo "[BENCHMARK] Signaling monitoring sidecar to stop..."
            touch ${STATE_DIR}/.stop_collection

            # Wait for monitoring to complete (max 60 seconds)
            echo "[BENCHMARK] Waiting for monitoring to complete..."
            for i in {1..60}; do
              if [ ! -f "${STATE_DIR}/.healthy" ]; then
                echo "[BENCHMARK] Monitoring sidecar completed"
                break
              fi
              sleep 1
            done
            {{- end }}

            echo "[BENCHMARK] Results saved to ${RUN_DIR}"

            # Create a marker file to signal the s3-uploader to start
            echo "${RUN_DIR}" > /results/upload-marker

            echo "[JOB] Benchmark script finished. Waiting for S3 upload to complete..."
            # Wait for the sidecar to remove the marker file
            while [ -f "/results/upload-marker" ]; do
              sleep 5
            done
            echo "[JOB] S3 upload complete. Exiting."
        volumeMounts:
        - name: results
          mountPath: /results
        {{- if .Values.monitoring.enabled }}
        - name: shared-state
          mountPath: /shared/state
        {{- end }}
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
      {{- if .Values.s3.enabled }}
      - name: s3-uploader
        image: "amazon/aws-cli:latest"
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.s3.secretName }}
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.s3.secretName }}
                key: AWS_SECRET_ACCESS_KEY
        command: ["/bin/bash"]
        args:
          - -c
          - |
            set -e
            DONE_FILE_PATH="/results/upload-marker"

            trap 'rm -f ${DONE_FILE_PATH}' EXIT

            echo "[JOB] S3 uploader started, waiting for benchmark to complete..."

            SECONDS=0
            while [ ! -f "${DONE_FILE_PATH}" ]; do
              echo -ne "[JOB] Waiting for benchmark completion marker (${SECONDS}s)\r"
              sleep 1
            done
            echo ""

            RUN_DIR=$(cat "${DONE_FILE_PATH}")
            OUTPUT_FILE="${RUN_DIR}/output.json"

            if [ -f "${OUTPUT_FILE}" ]; then
              echo "[JOB] Benchmark complete. Uploading results to S3 from ${OUTPUT_FILE}..."
              # Try to upload, but do not exit on error
              aws s3 cp "${OUTPUT_FILE}" "s3://{{ .Values.s3.bucket }}/llm-d-bench/$(basename ${RUN_DIR})/output.json" --region {{ .Values.s3.region }} || \
                echo "[JOB] Error: S3 upload failed. The job will still complete."
              echo "[JOB] Results successfully uploaded to S3 bucket: {{ .Values.s3.bucket }}"
            else
              echo "[JOB] Error: Output file not found at ${OUTPUT_FILE}. Skipping upload."
            fi

            echo "[JOB] S3 uploader finished."
        volumeMounts:
        - name: results
          mountPath: /results
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
      {{- end }}

      {{- if .Values.monitoring.enabled }}
      # Monitoring sidecar container
      - name: monitoring
        image: "{{ .Values.monitoring.sidecar.image.repository }}:{{ .Values.monitoring.sidecar.image.tag }}"
        env:
          - name: THANOS_URL
            value: {{ .Values.monitoring.thanosUrl | quote }}
          - name: RESULTS_BASE_DIR
            value: "/results"
          - name: COLLECTION_INTERVAL
            value: {{ .Values.monitoring.collectionInterval | quote }}
          {{- if .Values.monitoring.metrics }}
          - name: METRICS
            value: {{ join "," .Values.monitoring.metrics | quote }}
          {{- end }}
          {{- if .Values.monitoring.labels }}
          - name: LABELS
            value: {{ .Values.monitoring.labels | quote }}
          {{- end }}
          - name: COLLECT_NODE_METRICS
            value: {{ .Values.monitoring.collectNodeMetrics | quote }}
          - name: LOG_LEVEL
            value: {{ .Values.monitoring.logLevel | quote }}
        volumeMounts:
        - name: results
          mountPath: /results
        - name: shared-state
          mountPath: /tmp/monitoring
        resources:
          requests:
            memory: {{ .Values.monitoring.sidecar.resources.requests.memory | quote }}
            cpu: {{ .Values.monitoring.sidecar.resources.requests.cpu | quote }}
          limits:
            memory: {{ .Values.monitoring.sidecar.resources.limits.memory | quote }}
            cpu: {{ .Values.monitoring.sidecar.resources.limits.cpu | quote }}
        # Liveness probe to ensure monitoring is responsive
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "[ -f /tmp/monitoring/.healthy ]"
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        # Readiness probe to track when monitoring is ready
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "[ -f /tmp/monitoring/.healthy ]"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      {{- end }}

      volumes:
      - name: results
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}
      {{- if .Values.monitoring.enabled }}
      - name: shared-state
        emptyDir: {}
      {{- end }}
      restartPolicy: Never
      {{- if .Values.benchmark.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.benchmark.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.benchmark.affinity }}
      affinity:
        {{- toYaml .Values.benchmark.affinity | nindent 8 }}
      {{- end }}
  backoffLimit: 2
{{- end }}
