---
apiVersion: v1
kind: Namespace
metadata:
  name: github-runners
  labels:
    name: github-runners
---
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: github-runners
type: Opaque
stringData:
  # GitHub Personal Access Token (PAT)
  # Create at: https://github.com/settings/tokens/new
  # Required scopes:
  #   - For repository runners: repo (full control)
  #   - For organization runners: repo + admin:org
  github_token: "${GITHUB_TOKEN}"
  github_owner: "${GITHUB_OWNER}"
  github_repo: "${GITHUB_REPOSITORY}"
