---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actions-runner-controller
  namespace: github-runners
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: actions-runner-controller
  namespace: github-runners
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: actions-runner-controller
  namespace: github-runners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: actions-runner-controller
subjects:
- kind: ServiceAccount
  name: actions-runner-controller
  namespace: github-runners
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runner
  namespace: github-runners
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-runner
  namespace: github-runners
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-runner
  namespace: github-runners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-runner
subjects:
- kind: ServiceAccount
  name: github-runner
  namespace: github-runners
