---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions-deployer
  namespace: llm-d-inference-scheduling
rules:
  # Permissions for Helm to manage resources
  - apiGroups: [""]
    resources:
      - persistentvolumeclaims
      - pods
      - pods/log
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Permissions for managing Jobs
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Permissions for Helm releases
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
