---
apiVersion: v1
kind: Namespace
metadata:
  name: mlflow
  labels:
    name: mlflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow-sa
  namespace: mlflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mlflow-nonroot-scc
  namespace: mlflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:nonroot
subjects:
- kind: ServiceAccount
  name: mlflow-sa
  namespace: mlflow
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: mlflow
type: Opaque
stringData:
  POSTGRES_USER: mlflow
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: mlflow
---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-s3-secret
  namespace: mlflow
type: Opaque
stringData:
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  bucket-name: ${S3_BUCKET_NAME}
  region: ${AWS_REGION}
---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-auth
  namespace: mlflow
type: Opaque
stringData:
  admin-username: ${MLFLOW_ADMIN_USERNAME:-admin}
  admin-password: ${MLFLOW_ADMIN_PASSWORD}