---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: mlflow
data:
  nginx.conf: |
    pid /var/run/nginx/nginx.pid;
    events {
        worker_connections 1024;
    }
    http {
        client_body_temp_path /var/cache/nginx/client_body;
        proxy_temp_path /var/cache/nginx/proxy_temp;
        fastcgi_temp_path /var/cache/nginx/fastcgi_temp;
        uwsgi_temp_path /var/cache/nginx/uwsgi_temp;
        scgi_temp_path /var/cache/nginx/scgi_temp;

        server {
            listen 8080;
            location /health {
                proxy_pass http://localhost:5000/health;
                proxy_set_header Host $host;
            }
            location / {
                auth_basic "MLflow Authentication";
                auth_basic_user_file /etc/nginx-auth/htpasswd;
                proxy_pass http://localhost:5000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
  create_htpasswd.sh: |
    #!/bin/sh
    set -e
    
    USERNAME="${ADMIN_USER}"
    PASSWORD="${ADMIN_PASS}"
    
    echo "Creating htpasswd file for user: ${USERNAME}"
    
    apk add --no-cache apache2-utils
    htpasswd -bc /etc/nginx-auth/htpasswd "${USERNAME}" "${PASSWORD}"
    
    echo "htpasswd file created successfully"
    echo "File contents:"
    cat /etc/nginx-auth/htpasswd
    echo ""
    echo "File permissions:"
    ls -la /etc/nginx-auth/htpasswd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      serviceAccountName: mlflow-sa
      securityContext:
        runAsNonRoot: true
        fsGroup: 0
        fsGroupChangePolicy: "OnRootMismatch"
      initContainers:
      - name: wait-for-postgres
        image: registry.redhat.io/rhel9/postgresql-15:latest
        command:
        - /bin/bash
        - -c
        - |
          until pg_isready -h postgresql -p 5432 -U mlflow; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          echo "PostgreSQL is ready"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      
      - name: setup-htpasswd
        image: registry.access.redhat.com/ubi9/httpd-24:latest
        command:
        - /bin/sh
        - -c
        - |
          set -e
          USERNAME="${ADMIN_USER}"
          PASSWORD="${ADMIN_PASS}"
          
          echo "Creating htpasswd file for user: ${USERNAME}"
          
          # Use htpasswd command (already installed in httpd image)
          htpasswd -bc /etc/nginx-auth/htpasswd "${USERNAME}" "${PASSWORD}"
          
          echo "htpasswd file created successfully"
          echo "File contents:"
          cat /etc/nginx-auth/htpasswd
          echo ""
          echo "File permissions:"
          ls -la /etc/nginx-auth/htpasswd
        env:
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: mlflow-auth
              key: admin-username
        - name: ADMIN_PASS
          valueFrom:
            secretKeyRef:
              name: mlflow-auth
              key: admin-password
        volumeMounts:
        - name: nginx-auth
          mountPath: /etc/nginx-auth
        securityContext:
          runAsUser: 1001
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v2.18.0
        command: ["/bin/bash", "-c"]
        args:
        - |
          set -e
          
          # Use proper application directory instead of /tmp
          export HOME=/opt/mlflow
          export PIP_CACHE_DIR=/opt/mlflow/.cache/pip
          export PYTHONUSERBASE=/opt/mlflow/.local
          
          # Create directories with proper permissions
          mkdir -p /opt/mlflow/.cache/pip /opt/mlflow/.local
          
          # Install dependencies to user location
          pip install --user --no-warn-script-location psycopg2-binary boto3
          
          # Update PATH
          export PATH="/opt/mlflow/.local/bin:$PATH"
          export PYTHONPATH="/opt/mlflow/.local/lib/python3.10/site-packages:$PYTHONPATH"

          # Read secrets
          export POSTGRES_USER=$(cat /etc/secrets/postgres/POSTGRES_USER)
          export POSTGRES_PASSWORD=$(cat /etc/secrets/postgres/POSTGRES_PASSWORD)
          export S3_BUCKET=$(cat /etc/secrets/s3/bucket-name)

          # Start MLflow server (no auth, nginx handles it)
          exec mlflow server \
            --backend-store-uri "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/mlflow" \
            --default-artifact-root "s3://${S3_BUCKET}/" \
            --host 127.0.0.1 \
            --port 5000
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mlflow-s3-secret
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mlflow-s3-secret
              key: secret-key
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: mlflow-s3-secret
              key: region
        volumeMounts:
        - name: postgres-secret
          mountPath: /etc/secrets/postgres
          readOnly: true
        - name: s3-secret
          mountPath: /etc/secrets/s3
          readOnly: true
        - name: mlflow-home
          mountPath: /opt/mlflow
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 2Gi
      
      - name: nginx
        image: nginx:alpine
        command:
        - /bin/sh
        - -c
        - |
          # Create required directories for nginx
          mkdir -p /var/run/nginx /var/cache/nginx/client_body /var/cache/nginx/proxy_temp \
                   /var/cache/nginx/fastcgi_temp /var/cache/nginx/uwsgi_temp /var/cache/nginx/scgi_temp
          
          # Start nginx
          exec nginx -g 'daemon off;'
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: nginx-auth
          mountPath: /etc/nginx-auth
          readOnly: true
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run/nginx
        securityContext:
          runAsUser: 101
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
      
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu
                operator: DoesNotExist
              - key: nvidia.com/gpu.present
                operator: DoesNotExist
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: nginx-auth
        emptyDir: {}
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      - name: postgres-secret
        secret:
          secretName: postgresql-secret
      - name: s3-secret
        secret:
          secretName: mlflow-s3-secret
      - name: mlflow-home
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlflow
  labels:
    app: mlflow
spec:
  ports:
  - port: 5000
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: mlflow
  type: ClusterIP